package com.creditsuisse.loanpreapprovaldmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer monthlyIncome;

	private java.lang.Integer creditScore;

	private java.lang.Integer additionalExpenses;

	public Applicant() {
	}

	public java.lang.Integer getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(java.lang.Integer monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public java.lang.Integer getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		this.creditScore = creditScore;
	}

	public java.lang.Integer getAdditionalExpenses() {
		return this.additionalExpenses;
	}

	public void setAdditionalExpenses(java.lang.Integer additionalExpenses) {
		this.additionalExpenses = additionalExpenses;
	}

	public Applicant(java.lang.Integer monthlyIncome,
			java.lang.Integer creditScore, java.lang.Integer additionalExpenses) {
		this.monthlyIncome = monthlyIncome;
		this.creditScore = creditScore;
		this.additionalExpenses = additionalExpenses;
	}

}