package com.creditsuisse.loanpreapprovaldmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer housingExpense;
	private java.lang.Integer monthlyIncome;

	private java.lang.Integer creditScore;

	public Applicant() {
	}

	public java.lang.Integer getHousingExpense() {
		return this.housingExpense;
	}

	public void setHousingExpense(java.lang.Integer housingExpense) {
		this.housingExpense = housingExpense;
	}

	public java.lang.Integer getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(java.lang.Integer monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public java.lang.Integer getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		this.creditScore = creditScore;
	}

	public Applicant(java.lang.Integer housingExpense,
			java.lang.Integer monthlyIncome, java.lang.Integer creditScore) {
		this.housingExpense = housingExpense;
		this.monthlyIncome = monthlyIncome;
		this.creditScore = creditScore;
	}

}